version: '3'
services:
  pgsql:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pgsql
    tty: true
    volumes:
      - ./db:/var/lib/postgresql/data
    ports:
      - '25432:5432'